### ISSUE TITLE
Add API for AJAX requests

### ISSUE THREAD

**Issue by cramertj** [cramertj/domafic-rs#2]

**Comment by LooMaclin** [comment]
Nice! I'm waiting for it. =)
Next, you can try add WebSocket API support and AJAX support based on futures.

**Comment by beatgammit** [comment]
This seems like it already exists in [domafic::web_render::HttpRequest](https://github.com/cramertj/domafic-rs/blob/master/src/web_render.rs#L130), no? [Example](https://github.com/cramertj/domafic-rs/blob/e2c814dec3903ba76644120561f8a04f90b94171/examples/http_echo.rs).

**Comment by cramertj** [comment]
@beatgammit Yep! There are some improvements I want to make, but those can be tracked separately. I think it makes sense to close this issue.
