### ISSUE TITLE
Do not recreate Dom at each rendering pass

### ISSUE THREAD

**Issue by bestouff** [cramertj/domafic-rs#6]
_Disclaimer: I know next to nothing_
It looks like the Dom is deleted and recreated each time there's a rendering pass, whereas in a typical js setup I would create the Dom once and just update its data when needed. Isn't that a bit heavy on the browser ?
(Note that I didn't do any perf test to add credibility to my random thought)

**Comment by cramertj** [comment]
There's actually an internal DOM representation similar to how React or Elm work. When `render` is called, the result is diff'ed with the last rendered DOM, and the changes are applied.

**Comment by cramertj** [comment]
I'm going to close this. Feel free to reopen if I didn't fully clarify the behavior, or if there's some more advanced behavior you're looking for.

**Comment by bestouff** [comment]
Aaah perfect ! Thanks for the clarification.
